# Generated by Django 4.2.20 on 2025-04-26 02:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smarthrm.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0001_initial'),
        ('factories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên chức danh')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã chức danh')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('department_type', models.CharField(choices=[('all', 'Tất cả'), ('department', 'Phòng ban'), ('factory', 'Xí nghiệp')], default='all', max_length=20, verbose_name='Áp dụng cho')),
                ('position_type', models.CharField(choices=[('employee', 'Nhân viên'), ('deputy', 'Phó phòng'), ('manager', 'Trưởng phòng'), ('director', 'Giám đốc'), ('other', 'Khác')], default='employee', max_length=20, verbose_name='Loại chức vụ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Chức danh',
                'verbose_name_plural': 'Danh sách chức danh',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã nhân viên')),
                ('attendance_code', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Mã chấm công')),
                ('first_name', models.CharField(max_length=50, verbose_name='Tên')),
                ('last_name', models.CharField(max_length=50, verbose_name='Họ và tên đệm')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='Họ và tên đầy đủ')),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10, verbose_name='Giới tính')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Số điện thoại phải có định dạng: '+999999999'. Tối đa 15 chữ số.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Số điện thoại')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=smarthrm.utils.employee_avatar_path, verbose_name='Ảnh đại diện')),
                ('join_date', models.DateField(verbose_name='Ngày vào làm')),
                ('contract_type', models.CharField(choices=[('pending', 'Chờ tạo'), ('probation', 'Thử việc'), ('full_time', 'Chính thức')], default='probation', max_length=20, verbose_name='Loại hợp đồng')),
                ('workplace_type', models.CharField(choices=[('department', 'Phòng ban'), ('factory', 'Xí nghiệp')], default='department', max_length=20, verbose_name='Loại nơi làm việc')),
                ('permanent_address', models.TextField(verbose_name='Địa chỉ thường trú')),
                ('current_address', models.TextField(verbose_name='Địa chỉ hiện tại')),
                ('id_card_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số CCCD/CMND')),
                ('id_card_issue_date', models.DateField(blank=True, null=True, verbose_name='Ngày cấp')),
                ('id_card_issue_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nơi cấp')),
                ('id_card_front_image', models.ImageField(blank=True, null=True, upload_to=smarthrm.utils.employee_id_card_path, verbose_name='Ảnh mặt trước CCCD')),
                ('id_card_back_image', models.ImageField(blank=True, null=True, upload_to=smarthrm.utils.employee_id_card_path, verbose_name='Ảnh mặt sau CCCD')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang làm việc')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('active', 'Đang làm việc'), ('probation', 'Thử việc'), ('failed_probation', 'Không đạt thử việc'), ('leave', 'Nghỉ phép'), ('suspended', 'Tạm đình chỉ'), ('terminated', 'Đã nghỉ việc')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('password_changed', models.BooleanField(default=False, verbose_name='Đã đổi mật khẩu')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='departments.department', verbose_name='Phòng ban')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='factories.factory', verbose_name='Xí nghiệp')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.jobtitle', verbose_name='Chức danh')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
                'ordering': ['code', 'last_name', 'first_name'],
            },
        ),
    ]
