# Generated by Django 5.2 on 2025-04-28 15:10

import django.db.models.deletion
import recruitment.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('factories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('education', models.TextField(verbose_name='Học vấn')),
                ('experience', models.TextField(verbose_name='Kinh nghiệm làm việc')),
                ('skills', models.TextField(verbose_name='Kỹ năng')),
                ('resume', models.FileField(upload_to=recruitment.models.resume_file_path, verbose_name='CV')),
                ('cover_letter', models.TextField(blank=True, null=True, verbose_name='Thư xin việc')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('screening', 'Đang sàng lọc'), ('interview_department', 'Phỏng vấn phòng ban'), ('interview_factory', 'Phỏng vấn xí nghiệp'), ('offered', 'Đã đề xuất'), ('accepted', 'Đã chấp nhận'), ('rejected', 'Từ chối'), ('cancelled', 'Đã hủy')], default='new', max_length=30, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Đơn ứng tuyển',
                'verbose_name_plural': 'Đơn ứng tuyển',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('department', 'Phòng ban'), ('factory', 'Xí nghiệp'), ('hr', 'Nhân sự')], max_length=20, verbose_name='Loại phỏng vấn')),
                ('scheduled_date', models.DateTimeField(verbose_name='Thời gian phỏng vấn')),
                ('location', models.CharField(max_length=100, verbose_name='Địa điểm phỏng vấn')),
                ('status', models.CharField(choices=[('scheduled', 'Đã lên lịch'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='scheduled', max_length=20, verbose_name='Trạng thái')),
                ('result', models.CharField(choices=[('pending', 'Chưa có kết quả'), ('passed', 'Đạt'), ('failed', 'Không đạt')], default='pending', max_length=20, verbose_name='Kết quả')),
                ('evaluation', models.TextField(blank=True, null=True, verbose_name='Đánh giá')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_interviews', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('interviewers', models.ManyToManyField(related_name='conducted_interviews', to=settings.AUTH_USER_MODEL, verbose_name='Người phỏng vấn')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.jobapplication', verbose_name='Đơn ứng tuyển')),
            ],
            options={
                'verbose_name': 'Phỏng vấn',
                'verbose_name_plural': 'Phỏng vấn',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('job_code', models.CharField(max_length=50, unique=True, verbose_name='Mã tin tuyển dụng')),
                ('description', models.TextField(verbose_name='Mô tả công việc')),
                ('requirements', models.TextField(verbose_name='Yêu cầu')),
                ('benefits', models.TextField(verbose_name='Quyền lợi')),
                ('positions', models.PositiveIntegerField(default=1, verbose_name='Số lượng cần tuyển')),
                ('min_salary', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Lương tối thiểu')),
                ('max_salary', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Lương tối đa')),
                ('is_salary_visible', models.BooleanField(default=False, verbose_name='Hiển thị lương')),
                ('workplace_type', models.CharField(choices=[('department', 'Phòng ban'), ('factory', 'Xí nghiệp')], default='department', max_length=20, verbose_name='Loại nơi làm việc')),
                ('location', models.CharField(max_length=100, verbose_name='Địa điểm làm việc')),
                ('publish_date', models.DateField(verbose_name='Ngày đăng')),
                ('closing_date', models.DateField(verbose_name='Ngày hết hạn')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('pending', 'Chờ duyệt'), ('published', 'Đã đăng'), ('closed', 'Đã đóng'), ('cancelled', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày phê duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_job_postings', to=settings.AUTH_USER_MODEL, verbose_name='Người phê duyệt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_postings', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to='departments.department', verbose_name='Phòng ban')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to='factories.factory', verbose_name='Xí nghiệp')),
            ],
            options={
                'verbose_name': 'Tin tuyển dụng',
                'verbose_name_plural': 'Tin tuyển dụng',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.jobposting', verbose_name='Tin tuyển dụng'),
        ),
    ]
