# Generated by Django 5.2 on 2025-04-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='is_open_until_filled',
            field=models.BooleanField(default=False, verbose_name='Tuyển dụng đến khi đủ'),
        ),
    ]
