# Generated by Django 5.2 on 2025-04-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_jobposting_is_open_until_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='is_salary_negotiable',
            field=models.BooleanField(default=False, verbose_name='Lương thỏa thuận'),
        ),
    ]
