# Generated by Django 5.2 on 2025-04-29 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('recruitment', '0003_jobposting_is_salary_negotiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='division',
            field=models.ForeignKey(blank=True, limit_choices_to={'dept_type': 'division'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_job_postings', to='departments.department', verbose_name='Bộ phận'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='team',
            field=models.ForeignKey(blank=True, limit_choices_to={'dept_type': 'team'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_job_postings', to='departments.department', verbose_name='Nhóm'),
        ),
    ]
