# Generated by Django 5.2 on 2025-04-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_jobposting_division_jobposting_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='education_required',
            field=models.CharField(choices=[('none', 'Không yêu cầu bằng cấp'), ('high_school', 'Tốt nghiệp THPT'), ('vocational', 'Trung cấp nghề'), ('college', 'Cao đẳng'), ('bachelor', 'Đại học'), ('master', 'Thạc sĩ'), ('phd', 'Tiến sĩ')], default='bachelor', max_length=20, verbose_name='Học vấn'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Toàn thời gian'), ('part_time', 'Bán thời gian'), ('contract', 'Hợp đồng'), ('temporary', 'Tạm thời'), ('internship', 'Thực tập')], default='full_time', max_length=20, verbose_name='Hình thức làm việc'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Mới tốt nghiệp'), ('junior', 'Sơ cấp (1-2 năm)'), ('mid', 'Trung cấp (3-5 năm)'), ('senior', 'Cao cấp (5+ năm)'), ('lead', 'Nhóm trưởng/Quản lý'), ('executive', 'Điều hành cấp cao')], default='entry', max_length=20, verbose_name='Kinh nghiệm'),
        ),
    ]
