# Generated by Django 5.2 on 2025-04-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_jobposting_education_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='job_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã tin tuyển dụng'),
        ),
    ]
