# Generated by Django 5.2 on 2025-04-29 04:36

import recruitment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_alter_jobposting_job_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=recruitment.models.avatar_image_path, verbose_name='Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nơi sinh'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên người liên hệ khẩn cấp'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại liên hệ khẩn cấp'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mối quan hệ'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dân tộc'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Mức lương mong muốn'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='family_policy_detail',
            field=models.TextField(blank=True, null=True, verbose_name='Chi tiết chính sách'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='family_policy_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Loại chính sách'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên cha'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='father_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại cha'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tên'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], default='male', max_length=10, verbose_name='Giới tính'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='id_card_back_image',
            field=models.ImageField(blank=True, null=True, upload_to=recruitment.models.id_card_image_path, verbose_name='Ảnh mặt sau CCCD/CMND'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='id_card_front_image',
            field=models.ImageField(blank=True, null=True, upload_to=recruitment.models.id_card_image_path, verbose_name='Ảnh mặt trước CCCD/CMND'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='id_card_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày cấp CCCD/CMND'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='id_card_issue_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nơi cấp CCCD/CMND'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số CCCD/CMND'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_family_policy',
            field=models.BooleanField(default=False, verbose_name='Thuộc diện chính sách'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Họ và tên đệm'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Độc thân'), ('married', 'Đã kết hôn'), ('divorced', 'Đã ly hôn'), ('widowed', 'Góa phụ')], max_length=20, null=True, verbose_name='Tình trạng hôn nhân'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='military_service',
            field=models.BooleanField(default=False, verbose_name='Đã hoàn thành nghĩa vụ quân sự'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='military_service_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu nghĩa vụ quân sự'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='military_service_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc nghĩa vụ quân sự'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='military_service_role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chức vụ trong quân đội'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên mẹ'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại mẹ'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='nationality',
            field=models.CharField(blank=True, default='Việt Nam', max_length=50, null=True, verbose_name='Quốc tịch'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='permanent_address',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ thường trú'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True, verbose_name='Liên kết portfolio'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tôn giáo'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='salary_currency',
            field=models.CharField(choices=[('VND', 'VND'), ('USD', 'USD'), ('EUR', 'EUR')], default='VND', max_length=5, verbose_name='Đơn vị tiền tệ'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='address',
            field=models.TextField(verbose_name='Địa chỉ liên hệ'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True, null=True, verbose_name='Thư giới thiệu'),
        ),
    ]
