# Generated by Django 5.2 on 2025-04-29 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_jobapplication_avatar_jobapplication_birth_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyPolicyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Loại chính sách gia đình',
                'verbose_name_plural': 'Loại chính sách gia đình',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=50, verbose_name='Tên')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Tình trạng hôn nhân',
                'verbose_name_plural': 'Tình trạng hôn nhân',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='family_policy_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.familypolicytype', verbose_name='Loại chính sách'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.maritalstatus', verbose_name='Tình trạng hôn nhân'),
        ),
    ]
