# Generated by Django 5.2 on 2025-04-29 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_familypolicytype_maritalstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Trình độ học vấn',
                'verbose_name_plural': 'Trình độ học vấn',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=50, verbose_name='Tên')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Giới tính',
                'verbose_name_plural': 'Giới tính',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='education',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='education_detail',
            field=models.TextField(blank=True, null=True, verbose_name='Chi tiết học vấn'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.educationlevel', verbose_name='Trình độ học vấn'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.gender', verbose_name='Giới tính'),
        ),
    ]
