# Generated by Django 5.2 on 2025-04-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_educationlevel_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_party_member',
            field=models.BooleanField(default=False, verbose_name='Là Đảng viên'),
        ),
    ]
