# Generated by Django 5.2 on 2025-04-29 10:05

import recruitment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_jobapplication_is_party_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='experience',
            field=models.TextField(blank=True, null=True, verbose_name='Kinh nghiệm làm việc'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=recruitment.models.resume_file_path, verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Kỹ năng'),
        ),
    ]
