# Generated by Django 4.2.20 on 2025-04-26 02:53

import assets.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên tài sản')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã tài sản')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Số serial')),
                ('asset_type', models.CharField(choices=[('assigned', 'Tài sản được cấp'), ('managed', 'Tài sản được quản lý')], default='assigned', max_length=20, verbose_name='Loại quản lý')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Ngày mua')),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Giá mua')),
                ('warranty_end_date', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn bảo hành')),
                ('supplier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nhà cung cấp')),
                ('status', models.CharField(choices=[('available', 'Sẵn sàng cấp phát'), ('assigned', 'Đã cấp phát'), ('maintenance', 'Đang bảo trì'), ('retired', 'Đã thanh lý'), ('lost', 'Mất/Thất lạc')], default='available', max_length=20, verbose_name='Trạng thái')),
                ('image', models.ImageField(blank=True, null=True, upload_to=assets.models.asset_image_path, verbose_name='Hình ảnh')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Tài sản',
                'verbose_name_plural': 'Tài sản',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên loại tài sản')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã loại')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Loại tài sản',
                'verbose_name_plural': 'Loại tài sản',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề kiểm kê')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('status', models.CharField(choices=[('planned', 'Kế hoạch'), ('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='planned', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_inventories', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Kiểm kê tài sản',
                'verbose_name_plural': 'Kiểm kê tài sản',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(max_length=100, verbose_name='Loại bảo trì')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Chi phí')),
                ('status', models.CharField(choices=[('scheduled', 'Đã lên lịch'), ('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='scheduled', max_length=20, verbose_name='Trạng thái')),
                ('performed_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đơn vị thực hiện')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='assets.asset', verbose_name='Tài sản')),
            ],
            options={
                'verbose_name': 'Bảo trì tài sản',
                'verbose_name_plural': 'Bảo trì tài sản',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày cấp phát')),
                ('expected_return_date', models.DateField(blank=True, null=True, verbose_name='Ngày dự kiến trả')),
                ('returned_date', models.DateField(blank=True, null=True, verbose_name='Ngày đã trả')),
                ('status', models.CharField(choices=[('pending', 'Chờ bàn giao'), ('assigned', 'Đã bàn giao'), ('returned', 'Đã trả lại'), ('damaged', 'Hư hỏng'), ('lost', 'Mất/Thất lạc')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('condition_on_assignment', models.TextField(blank=True, null=True, verbose_name='Tình trạng khi cấp phát')),
                ('condition_on_return', models.TextField(blank=True, null=True, verbose_name='Tình trạng khi trả lại')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.asset', verbose_name='Tài sản')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL, verbose_name='Người cấp phát')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='employees.employee', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Cấp phát tài sản',
                'verbose_name_plural': 'Cấp phát tài sản',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory', verbose_name='Loại tài sản'),
        ),
        migrations.CreateModel(
            name='AssetInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chưa kiểm kê'), ('verified', 'Đã xác minh'), ('missing', 'Không tìm thấy'), ('damaged', 'Hư hỏng')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kiểm tra')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='assets.asset', verbose_name='Tài sản')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_assets', to=settings.AUTH_USER_MODEL, verbose_name='Người kiểm tra')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assets.assetinventory', verbose_name='Đợt kiểm kê')),
            ],
            options={
                'verbose_name': 'Chi tiết kiểm kê',
                'verbose_name_plural': 'Chi tiết kiểm kê',
                'unique_together': {('inventory', 'asset')},
            },
        ),
    ]
