# Generated by Django 5.2 on 2025-04-27 05:10

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã danh mục')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.documentcategory', verbose_name='Danh mục cha')),
            ],
            options={
                'verbose_name': 'Danh mục tài liệu',
                'verbose_name_plural': 'Danh mục tài liệu',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('document_number', models.CharField(max_length=50, unique=True, verbose_name='Số hiệu tài liệu')),
                ('document_type', models.CharField(choices=[('policy', 'Chính sách'), ('procedure', 'Quy trình'), ('form', 'Biểu mẫu'), ('report', 'Báo cáo'), ('contract', 'Hợp đồng'), ('other', 'Khác')], max_length=20, verbose_name='Loại tài liệu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Nội dung')),
                ('file', models.FileField(blank=True, null=True, upload_to=documents.models.document_file_path, verbose_name='Tệp đính kèm')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Phiên bản')),
                ('access_level', models.CharField(choices=[('public', 'Công khai'), ('internal', 'Nội bộ'), ('restricted', 'Hạn chế'), ('confidential', 'Bảo mật')], default='internal', max_length=20, verbose_name='Mức độ truy cập')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày phê duyệt')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Ngày hiệu lực')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Ngày hết hiệu lực')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL, verbose_name='Người phê duyệt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentcategory', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Tài liệu',
                'verbose_name_plural': 'Tài liệu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='Phiên bản')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Nội dung')),
                ('file', models.FileField(blank=True, null=True, upload_to=documents.models.document_file_path, verbose_name='Tệp đính kèm')),
                ('change_summary', models.TextField(verbose_name='Tóm tắt thay đổi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_versions', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='Tài liệu')),
            ],
            options={
                'verbose_name': 'Phiên bản tài liệu',
                'verbose_name_plural': 'Phiên bản tài liệu',
                'ordering': ['-created_at'],
                'unique_together': {('document', 'version')},
            },
        ),
    ]
