# Generated by Django 4.2.20 on 2025-04-26 02:53

from django.db import migrations, models
import smarthrm.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên công ty')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tên viết tắt')),
                ('tax_code', models.CharField(max_length=20, unique=True, verbose_name='Mã số thuế')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('representative', models.CharField(max_length=100, verbose_name='Người đại diện')),
                ('position', models.CharField(max_length=100, verbose_name='Chức vụ người đại diện')),
                ('hr_department', models.CharField(default='Phòng Nhân sự', max_length=100, verbose_name='Tên phòng nhân sự')),
                ('hr_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại phòng nhân sự')),
                ('career_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email tuyển dụng')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=smarthrm.utils.company_logo_path, verbose_name='Logo')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số Fax')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('foundation_date', models.DateField(blank=True, null=True, verbose_name='Ngày thành lập')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Công ty',
                'verbose_name_plural': 'Công ty',
            },
        ),
    ]
