# Generated by Django 4.2.20 on 2025-04-26 02:53

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('factory_type', models.CharField(choices=[('factory', 'Xí nghiệp'), ('division', 'Bộ phận'), ('team', 'Nhóm')], max_length=20, verbose_name='Loại')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên người quản lý')),
                ('manager_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chức danh người quản lý')),
                ('manager_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email người quản lý')),
                ('manager_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='SĐT người quản lý')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vị trí')),
                ('capacity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Công suất')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='Ngày thành lập')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factories', to='company.company', verbose_name='Công ty')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='factories.factory', verbose_name='Đơn vị cha')),
            ],
            options={
                'verbose_name': 'Xí nghiệp',
                'verbose_name_plural': 'Xí nghiệp',
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='BoPhanXiNghiep',
            fields=[
            ],
            options={
                'verbose_name': 'Bộ phận xí nghiệp',
                'verbose_name_plural': 'Bộ phận xí nghiệp',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('factories.factory',),
        ),
        migrations.CreateModel(
            name='NhomXiNghiep',
            fields=[
            ],
            options={
                'verbose_name': 'Nhóm xí nghiệp',
                'verbose_name_plural': 'Nhóm xí nghiệp',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('factories.factory',),
        ),
        migrations.CreateModel(
            name='XiNghiep',
            fields=[
            ],
            options={
                'verbose_name': 'Xí nghiệp',
                'verbose_name_plural': 'Xí nghiệp',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('factories.factory',),
        ),
    ]
