# Generated by Django 4.2.20 on 2025-04-26 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('notification_type', models.CharField(choices=[('system', 'Hệ thống'), ('document', 'Tài liệu'), ('task', 'Công việc'), ('message', 'Tin nhắn'), ('approval', 'Phê duyệt'), ('other', 'Khác')], default='system', max_length=20, verbose_name='Loại thông báo')),
                ('priority', models.CharField(choices=[('low', 'Thấp'), ('normal', 'Bình thường'), ('high', 'Cao'), ('urgent', 'Khẩn cấp')], default='normal', max_length=20, verbose_name='Mức độ ưu tiên')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID đối tượng')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đường dẫn')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian đọc')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa')),
                ('display_type', models.CharField(choices=[('popup', 'Popup'), ('toast', 'Toast'), ('badge', 'Badge'), ('email', 'Email'), ('sms', 'SMS')], default='toast', max_length=20, verbose_name='Kiểu hiển thị')),
                ('requires_action', models.BooleanField(default=False, verbose_name='Yêu cầu hành động')),
                ('action_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL hành động')),
                ('action_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nội dung nút hành động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hết hạn')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Loại đối tượng')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người gửi')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-created_at'],
            },
        ),
    ]
